name: Build embedded binaries

on:
  push:
    branches:
      - master

env:
  PUT_IO_TOKEN: ${{ secrets.PUT_IO_TOKEN }}
  PRIVATE_BINARIES_BUCKET: ${{ secrets.PRIVATE_BINARIES_BUCKET }}

jobs:
  setup-build-upload:
    name: Setup, Build, and Upload
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go

      - name: Setup gox
        run: go get github.com/mitchellh/gox

      - name: Setup packr2
        run: go get -u github.com/gobuffalo/packr/v2/packr2

      - name: Embed static files
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          GO111MODULE=on packr2 --verbose

      - name: Create private binaries
        run: |
          REPO_ROOT=$(git rev-parse --show-toplevel)
          export PATH=$PATH:$(go env GOPATH)/bin
          gox -os="darwin linux windows" -arch="amd64" -output="$REPO_ROOT/bin/{{.Dir}}_{{.OS}}_{{.Arch}}" -tags="embedded" -ldflags="-X 'main.putIOToken=${PUT_IO_TOKEN}'" .

      - name: Setup gcloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "286.0.0"
          service_account_email: ${{ secrets.RUN_SA_EMAIL }}
          service_account_key: ${{ secrets.RUN_SA_KEY }}
          project_id: ${{ secrets.RUN_PROJECT }}

      - name: Upload private binaries
        run: |
          gsutil cp bin/* gs://${PRIVATE_BINARIES_BUCKET}
